version: '3.9'

networks:
  proxy:
    name: backbone_proxy
    external: true

services:
  proxy:
    image: traefik:v2.10.5
    restart: always
    container_name: reverse_proxy
      #command:
      #- "--providers.file.filename=/traefik.ddyml" 
    labels:
      - traefik.enable=true
      - traefik.docker.network=backbone_proxy
      - traefik.http.routers.traefik.tls=true
      - traefik.http.routers.traefik.rule=Host("${APPLICATION_FQDN}")
      - traefik.http.routers.traefik.service=traefik-dashboard
      - traefik.http.services.traefik-dashboard.loadbalancer.server.port=8080
    ports:
      - "80:80"
      - "443:443" 
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./traefik/traefik.yml:/etc/traefik/traefik.yml:ro"
      - "./traefik/certs:/etc/certs:ro"
    networks:
      - proxy
