networks:
  proxy:
    name: backbone_proxy
    external: true
  monitoring:
    name: backbone_monitoring
    external: true

services:
  proxy:
    image: traefik:v3.1.6
    restart: always
    container_name: reverse_proxy
    labels:
      - traefik.enable=true
      - traefik.docker.network=backbone_proxy
      - traefik.http.routers.dashboard.ruleSyntax=v3
      - traefik.http.routers.dashboard.tls=true
      - traefik.http.routers.dashboard.entryPoints=https
      - traefik.http.routers.dashboard.rule=Host("${APPLICATION_FQDN}") && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))
      - traefik.http.routers.dashboard.service=api@internal
      - prometheus.scrape=true
      - prometheus.port=8080
    ports:
      - "80:80"
      - "443:443" 
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./traefik/conf/:/etc/traefik/:ro"
      - "./traefik/certs:/etc/certs:ro"
    networks:
      - proxy
      - monitoring
    healthcheck:
      test: ["CMD", "traefik", "healthcheck"]
      interval: 30s
      timeout: 3s
      retries: 30
